# Generated by Django 6.0.1 on 2026-01-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del curso', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL amigable generada automáticamente', unique=True)),
                ('descripcion', models.TextField(help_text='Descripción detallada del curso')),
                ('nivel', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Principiante', max_length=50)),
                ('instructor', models.CharField(help_text='Nombre del instructor', max_length=100)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en horas')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en USD', max_digits=8)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del curso')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa del curso', null=True, upload_to='cursos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
