# Generated by Django 6.0.1 on 2026-01-21 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_categoria_alter_curso_nivel_alter_curso_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(default=1, help_text='Categoría a la que pertenece el curso', on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.categoria'),
            preserve_default=False,
        ),
    ]
