# Generated by Django 6.0.1 on 2026-01-23 02:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('resumen', models.CharField(blank=True, help_text='Si lo dejas vacío, se generará automáticamente a partir del contenido.', max_length=300, verbose_name='Resumen (opcional)')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('etiquetas', models.CharField(blank=True, help_text='Separar con comas', max_length=200, verbose_name='Etiquetas')),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen destacada')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='blog.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-fecha_publicacion'],
                'indexes': [models.Index(fields=['slug'], name='blog_entrad_slug_6162a6_idx'), models.Index(fields=['publicado', 'fecha_publicacion'], name='blog_entrad_publica_8f8310_idx')],
            },
        ),
    ]
