# Generated by Django 6.0.1 on 2026-01-23 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para mostrar en secciones destacadas', verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='visitas',
            field=models.PositiveIntegerField(default=0, help_text='Contador de visitas (incrementar desde la vista)', verbose_name='Visitas'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['destacado'], name='blog_entrad_destaca_c32848_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['visitas'], name='blog_entrad_visitas_8c62e3_idx'),
        ),
    ]
